### ISSUE TITLE
Arte: Sprites Objetos Interactuables

### ISSUE THREAD

**Issue by ADDI01** [UCM-FDI-DISIA/KaosTeam#57]

**Comment by ChaoIsBalling** [comment]
![Roca](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/114423476/1393a1fa-70b9-4f8d-8201-7002425157ed)

**Comment by ChaoIsBalling** [comment]
![Jarron](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/114423476/1ccd3a27-f0a3-4483-af0b-271fad83e675)

**Comment by ChaoIsBalling** [comment]
![PalancaSheet](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/114423476/e8b98d69-9897-41bb-900f-b457ed806f3b)
