### ISSUE TITLE
Arte: Sprites Mejoras de Habilidades

### ISSUE THREAD

**Issue by ADDI01** [UCM-FDI-DISIA/KaosTeam#59]

**Comment by ChaoIsBalling** [comment]
![Bolsa](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/114423476/457c3401-4e96-4dad-846a-0a5d2d396122)
![Gancho](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/114423476/043fedf2-b843-4e3a-89bf-9976404efbcd)
![HuevoSheet](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/114423476/73312d7f-4ed9-47db-a33b-87bd37f80156)
