### ISSUE TITLE
Arte: Cucaracha (Enemigo Zona Cocina)

### ISSUE THREAD

**Issue by ADDI01** [UCM-FDI-DISIA/KaosTeam#72]

**Comment by Erisolo** [comment]
![Image](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/123541890/dff94d59-6842-425a-a8b5-c36938cd2d50)
![Image](https://github.com/UCM-FDI-DISIA/KaosTeam/assets/123541890/ec4090be-032c-4a4e-afc3-b2f20920eeb0)
